application_dir = "harmony"
label = "Harmony 17"
ftrack_label = "Harmony"
schema = "avalon-core:application-1.0"
executable = "harmony_17"
description = ""
icon ="harmony_icon"
ftrack_icon = '{}/app_icons/harmony.png'
