application_dir = "storyboardpro"
label = "Storyboard Pro 7"
ftrack_label = "Storyboard Pro"
schema = "avalon-core:application-1.0"
executable = "storyboardpro_7"
description = ""
icon ="storyboardpro_icon"
ftrack_icon = '{}/app_icons/storyboardpro.png'
